provider:
  name: faas

functions:
  facedetect:
    lang: go-opencv
    handler: ./facedetect
    image: alexellis2/facedetect:0.1
    environment:
      output_mode: "image"
      input_mode: "url"
